### ISSUE TITLE
File detail page checklist

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#102]
- [x] Restore section bottom margins
- [x] `<p>` tag sentence for each section explaining what they are

**Comment by palewire** [comment]
- [ ] Affixed nav
- [ ] More detail in the red background text about CAL-ACCESS so a noob will know what we're talking about
